import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Dashboard from "./dashboard/page";
import Skills from "./skills/page";
import Achievements from "./achievements/page";
import Experience from "./experience/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Om Shivhare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        <Dashboard />
        <Skills />
        <Experience />
        <Achievements />
        {children}</body>
    </html>
  );
}
